//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int id { get; set; }
        public string position_detail { get; set; }
        public string facilities { get; set; }
        public string depart { get; set; }
        public string transit { get; set; }
        public string starting { get; set; }
        public string descDetail { get; set; }
        public string scheduleDetail { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string meta_detail { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order_detail { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
